"""Create tbl_user with enums

Revision ID: 39e81932d242
Revises: 
Create Date: 2024-08-16 17:21:41.097639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e81932d242'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('md_client',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=True),
    sa.Column('client_mobile', sa.String(), nullable=True),
    sa.Column('client_email', sa.String(), nullable=True),
    sa.Column('client_cities_id', sa.Integer(), nullable=True),
    sa.Column('client_state_id', sa.Integer(), nullable=True),
    sa.Column('client_countri_id', sa.Integer(), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_md_client_client_id'), 'md_client', ['client_id'], unique=False)
    op.create_table('tbl_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('mobile_no', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('user_type', sa.Enum('SA', 'A', name='usertype'), nullable=True),
    sa.Column('otp', sa.String(), nullable=True),
    sa.Column('otp_status', sa.Enum('A', 'D', name='otpstatus'), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('password_status', sa.Enum('R', 'U', name='passwordstatus'), nullable=True),
    sa.Column('wrong_password_attempts', sa.Integer(), nullable=True),
    sa.Column('active_status', sa.Enum('A', 'D', name='activestatus'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_user_id'), 'tbl_user', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_user_user_email'), 'tbl_user', ['user_email'], unique=True)
    op.create_index(op.f('ix_tbl_user_user_name'), 'tbl_user', ['user_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_user_user_name'), table_name='tbl_user')
    op.drop_index(op.f('ix_tbl_user_user_email'), table_name='tbl_user')
    op.drop_index(op.f('ix_tbl_user_id'), table_name='tbl_user')
    op.drop_table('tbl_user')
    op.drop_index(op.f('ix_md_client_client_id'), table_name='md_client')
    op.drop_table('md_client')
    # ### end Alembic commands ###
